### ISSUE TITLE
get TAC is null

### ISSUE THREAD

**Issue by andyeason** [skygongque/douyin_signature#1]
![image](https://user-images.githubusercontent.com/10055146/85472575-98dcce80-b5e4-11ea-8a44-885ea136ff26.png)
https://www.iesdouyin.com/share/user/${uid}

**Comment by skygongque** [comment]
抖音官方可能改了分享页个人主页的链接

**Comment by andyeason** [comment]
是的，我看接口增加了sec_uid,并且js内隐藏了tac

**Comment by LoveLH** [comment]
> 抖音官方可能改了分享页个人主页的链接
好像昨天晚上改了，tac不直接在页面上体现了，不能直接获取，我还没找到拿到tac的方法，签名算法好像没变

**Comment by RIP-GitHub** [comment]
已经解决抖音web抓取，q：416828817

**Comment by skygongque** [comment]
请求https://www.amemv.com/share/user/${uid}可以得到tac
