### ISSUE TITLE
Can't get the data

### ISSUE THREAD

**Issue by kien-pham** [skygongque/douyin_signature#3]
It doesn't work, no data returned. The uid is correct but what I got is:
{"code":-1,"context":"Fail to get tac.","reason":"No such uid 62469202354.Try again if you sure uid is correct."}

**Comment by skygongque** [comment]
Douyin or TikTok's official web page doesn't return tac parameter, so we can't get douyin or TikTok's user data through this way. Try to reverse douyin app's API.
