### ISSUE TITLE
能否获取用户的喜欢？

### ISSUE THREAD

**Issue by big-F** [skygongque/douyin_signature#4]
当前代码下载个人主页运行完美。
请问是否有方法获取用户的喜欢？
再次感谢

**Comment by orzchen** [comment]
https://www.iesdouyin.com/web/api/v2/aweme/like/?sec_uid={用户id}&count={count}&max_cursor={max_cursor}&aid=1128&_signature={signatture}
这个接口

**Comment by big-F** [comment]
> [https://www.iesdouyin.com/web/api/v2/aweme/like/?sec_uid={用户id}&count={count}&max_cursor={max_cursor}&aid=1128&_signature={signatture}](https://www.iesdouyin.com/web/api/v2/aweme/like/?sec_uid=%7B%E7%94%A8%E6%88%B7id%7D&count=%7Bcount%7D&max_cursor=%7Bmax_cursor%7D&aid=1128&_signature=%7Bsignatture%7D)
> 这个接口

感谢。有空再试试。
